# Generated by Django 3.2.3 on 2021-06-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NasOrganisation',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('YOE', models.DateField()),
                ('staff_Strength', models.IntegerField()),
                ('id', models.AutoField(help_text='Unique Apprenticeship Number', primary_key=True, serialize=False)),
                ('area_of_Specialization', models.CharField(max_length=200)),
                ('stage', models.CharField(blank=True, choices=[('Pr', 'Promotion'), ('Ap', 'Appraisal'), ('Ha', 'Harmonisation'), ('In', 'Installation'), ('Su', 'Supervision'), ('Mo', 'Monitoring')], default='Pr', help_text='Apprencticeship Stage', max_length=2)),
                ('promotion_Officer', models.CharField(blank=True, max_length=200, null=True)),
                ('appraisal_Officer', models.CharField(blank=True, max_length=200, null=True)),
                ('harmonisation_Officer', models.CharField(blank=True, max_length=200, null=True)),
                ('installation_Officer', models.CharField(blank=True, max_length=200, null=True)),
                ('supervision_Officer', models.CharField(blank=True, max_length=200, null=True)),
                ('monitoring_Officer', models.CharField(blank=True, max_length=200, null=True)),
                ('provisional_approval', models.BooleanField(default=False)),
                ('DOPA', models.DateField(blank=True, null=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NasDB.sector')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NasDB.state')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NasDB.type')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
