# Generated by Django 3.2.3 on 2021-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasorganisation',
            name='stage',
            field=models.CharField(blank=True, choices=[('Promotion', 'Promotion'), ('Appraisal', 'Appraisal'), ('Harmonisation', 'Harmonisation'), ('Installation', 'Installation'), ('Supervision', 'Supervision'), ('Monitoring', 'Monitoring')], default='Promotion', help_text='Apprencticeship Stage', max_length=20),
        ),
    ]
