# Generated by Django 3.2.3 on 2021-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasDB', '0003_alter_nasorganisation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasorganisation',
            name='appraisal_report_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', help_text='YES or NO', max_length=5),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='certification_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='NO', help_text='YES or NO', max_length=5),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='certification_type',
            field=models.CharField(blank=True, choices=[('CERTIFICATE OF PARTICIPATION', 'CERTIFICATE OF PARTICIPATION'), ('CERTIFICATE OF COMPETENCY', 'CERTIFICATE OF COMPETENCY')], default='CERTIFICATE OF PARTICIPATION', help_text='Pick a Certification type', max_length=200),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='curriculum_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='NO', help_text='YES or NO', max_length=5),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='curriculum_type',
            field=models.CharField(blank=True, choices=[('ITF', 'ITF'), ('ORGANISATION DESIGN', 'ORGANISATION DESIGN'), ('OTHERS', 'OTHERS')], default='ITF', help_text='Pick Curriculum Type', max_length=200),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='harmonisation_report_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', help_text='YES or NO', max_length=5),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='installation_report_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', help_text='YES or NO', max_length=5),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='monitoring_report_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', help_text='YES or NO', max_length=5),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='promotional_report_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='NO', help_text='YES or NO', max_length=5),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='supervision_report_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', help_text='YES or NO', max_length=5),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='training_record_available',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('N/A', 'N/A')], default='NO', help_text='YES or NO', max_length=200),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='training_record_type',
            field=models.CharField(blank=True, choices=[('Log Book', 'Log Book'), ('Attendance Register', 'Attendance Register'), ('Daily Record Activity', 'Daily Record Activity'), ('None', 'None')], default='None', max_length=200),
        ),
    ]
