# Generated by Django 3.2.3 on 2021-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NasDB', '0004_auto_20210813_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasorganisation',
            name='contact_person',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nasorganisation',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
