# Generated by Django 3.2.3 on 2021-06-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'designation',
                'verbose_name_plural': 'designations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'division',
                'verbose_name_plural': 'divisions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'training',
                'verbose_name_plural': 'trainings',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StaffBio',
            fields=[
                ('surname', models.CharField(db_index=True, max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('othernames', models.CharField(blank=True, max_length=200)),
                ('DOB', models.DateField()),
                ('DOE', models.DateField(null=True)),
                ('staffId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('email_official', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile_phone', models.CharField(max_length=200, null=True, unique=True)),
                ('address', models.TextField(null=True)),
                ('diploma', models.CharField(blank=True, max_length=200)),
                ('bachelors_degree', models.CharField(max_length=200)),
                ('masters_degree', models.CharField(blank=True, max_length=200, null=True)),
                ('doctorate_degree', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='uploads/staff')),
                ('favQuote', models.TextField(null=True)),
                ('leave_Start', models.DateField(blank=True)),
                ('leave_End', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Absconded', 'Absconded'), ('Available', 'Available'), ('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Career Development', 'Career Development'), ('Sabbatical Leave', 'Sabbatical Leave')], default='av', max_length=20)),
                ('certification', models.ManyToManyField(blank=True, to='StaffDB.Certification')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StaffDB.designation')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StaffDB.division')),
                ('trainings_attended', models.ManyToManyField(to='StaffDB.Training')),
            ],
        ),
    ]
