# Generated by Django 3.2.3 on 2021-06-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbio',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffbio',
            name='favQuote',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffbio',
            name='status',
            field=models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Absconded', 'Absconded'), ('Available', 'Available'), ('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Career Development', 'Career Development'), ('Sabbatical Leave', 'Sabbatical Leave')], default='Available', max_length=20),
        ),
    ]
