# Generated by Django 3.2.3 on 2021-06-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SpecialInterventionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Special Intervention Progam',
                'verbose_name_plural': 'Special Intervention Progam',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TradeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Trade Area',
                'verbose_name_plural': 'Trade Areas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('slug', models.SlugField(max_length=4)),
            ],
            options={
                'verbose_name': 'Year',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('other_names', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile_phone', models.CharField(max_length=200, null=True, unique=True)),
                ('address', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='uploads/trainee')),
                ('account_Number', models.IntegerField()),
                ('bvn', models.IntegerField(primary_key=True, serialize=False)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTA.bank')),
                ('special_Intervention_Program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTA.specialinterventionprogram')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTA.state')),
                ('trade_Area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTA.tradearea')),
                ('year', models.ForeignKey(default=2021, max_length=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTA.year')),
            ],
        ),
    ]
