# Generated by Django 3.2.3 on 2021-08-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TTA', '0002_auto_20210610_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact_Person', models.CharField(max_length=200)),
                ('contact_Phone_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('account_Number', models.IntegerField()),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTA.bank')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTA.state')),
                ('trade_Area', models.ManyToManyField(help_text='Select as many trade areas as applicable', to='TTA.TradeArea')),
            ],
            options={
                'verbose_name': 'Centre',
                'verbose_name_plural': 'Centres',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='trainee',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTA.centre'),
        ),
    ]
